name: CI Build

on:
  workflow_run:
    workflows: ['CI Tests']
    branches: ['separate-workflows']
    types: 
      - completed

jobs:
  build:
    name: Build on Node.js ${{ matrix.node_version }} and Platform ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x, 14.x, 16.x]
        platform: [ubuntu-latest, mac-lastest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn install:ci

      - name: Building
        run: yarn build
