name: CI Tests and Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test on Node.js ${{ matrix.node_version }} and platform ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14.x, 16.x, 17.x]
        platform: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          args: install:ci

      - name: Install dependencies
        run: yarn install:ci

      - name: Run unit tests
        run: yarn test:unit

      - name: Prepare database and run integration tests...
        env:
          PORT: ${{ secrets.PORT }}
          EXPRESS_LISTEN_APP_PORT: ${{ secrets.EXPRESS_LISTEN_APP_PORT }}
          STRIPE_SECRET_API_KEY: ${{ secrets.STRIPE_SECRET_API_KEY_TEST }}
          STRIPE_API_VERSION: ${{ secrets.STRIPE_API_VERSION }}
          ELEPHANT_API_KEY: ${{ secrets.ELEPHANT_API_KEY_TEST }}
        run: |
          docker build -t be-a-savior/server -f Dockerfile.tests . \
          --build-arg PORT=${{ secrets.PORT }} \
          --build-arg EXPRESS_LISTEN_APP_PORT=${{ secrets.EXPRESS_LISTEN_APP_PORT }} \
          --build-arg ELEPHANT_API_KEY=${{ secrets.ELEPHANT_API_KEY_TEST }} \
          --build-arg STRIPE_SECRET_API_KEY=${{ secrets.STRIPE_SECRET_API_KEY_TEST }} \
          --build-arg GITHUB_ACTIONS=$GITHUB_ACTIONS \
          --no-cache

  build:
    name: Build on Node.js ${{ matrix.node_version }} and platform ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x, 14.x, 16.x, 17.x]
        platform: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn install:ci

      - name: Build
        run: yarn build

