name: CI Tests and Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test on Node.js ${{ matrix.node_version }} and platform ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x, 14.x, 16.x]
        platform: [ubuntu-latest, mac-lastest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          args: install:ci

      - name: Install dependencies
        run: yarn install:ci

      - name: Run unit tests
        run: yarn test:unit

      - name: Prepare database and run integration tests...
        env:
          STRIPE_SECRET_API_KEY: ${{ secrets.STRIPE_SECRET_API_KEY_TEST }}
          STRIPE_API_VERSION: ${{ secrets.STRIPE_API_VERSION }}
          ELEPHANT_API_KEY: ${{ secrets.ELEPHANT_API_KEY_TEST }}
        run: |
          docker build -t be-a-savior/server . \
          --build-arg ELEPHANT_API_KEY=${{ secrets.ELEPHANT_API_KEY_TEST }} \
          --build-arg STRIPE_SECRET_API_KEY=${{ secrets.STRIPE_SECRET_API_KEY }} \
          --build-arg GITHUB_ACTIONS=$GITHUB_ACTIONS \
          --no-cache

  clean:
    needs: test
    name: Clean test databases with Node.js ${{ matrix.node_version }} and platform ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.x]
        platform: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn install:ci

      - name: Clean test databases
        env:
          STRIPE_SECRET_API_KEY: ${{ secrets.STRIPE_SECRET_API_KEY_TEST }}
          ELEPHANT_API_KEY: ${{ secrets.ELEPHANT_API_KEY_TEST }}
        run: |
          yarn clean:elephant:instances:team
    
  build:
    name: Build on Node.js ${{ matrix.node_version }} and platform ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x, 14.x, 16.x]
        platform: [ubuntu-latest, mac-lastest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn install:ci

      - name: Build
        run: yarn build

  deploy:
    name: Deploy on Node.js ${{ matrix.node_version }} and Platform ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.x]
        platform: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Deploy to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          # Below you must provide variables for your Heroku app.

          # The email address associated with your Heroku account.
          # If you don't want to use repository secrets (which is recommended) you can do:
          # email: my.email@example.com
          email: ${{ secrets.HEROKU_EMAIL }}
          
          # Heroku API key associated with provided user's email.
          # Api Key is available under your Heroku account settings.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # (Optional, default: "./")
          # Dockerfile directory.
          # For example, if you have a Dockerfile in the root of your project, leave it as follows:
          dockerfile_directory: ./

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: Dockerfile.production

          # (Optional, default: "")
          # Additional options of docker build command.
          docker_options: "--no-cache"

          # (Optional, default: "web")
          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          # For more information look at https://devcenter.heroku.com/articles/process-model
          process_type: web
