name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Test on ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          args: install:ci

      - name: Install dependencies...
        run: yarn install:ci

      - name: Building...
        run: yarn build

      - name: Testing server...
        run: yarn test:ci
        env:
          EXPRESS_LISTEN_APP_PORT: ${{ env.EXPRESS_LISTEN_APP_PORT }}
          STRIPE_PUBLISH_API_KEY: ${{ env.STRIPE_PUBLISH_API_KEY }}
          STRIPE_SECRET_API_KEY: ${{ env.STRIPE_SECRET_API_KEY }}
          STRIPE_API_VERSION: ${{ env.STRIPE_API_VERSION }}
