name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Test on ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          args: install:ci

      - name: Install dependencies...
        run: yarn install:ci

      - name: Run unit tests...
        run: yarn test:unit

      - name: Prepare database and run integration tests...
        run: |
          docker build -t be-a-savior/server . \
          --build-arg ELEPHANT_API_KEY=${{ secrets.ELEPHANT_API_KEY_TEST }} \
          --build-arg STRIPE_SECRET_API_KEY=${{ secrets.STRIPE_SECRET_API_KEY }} \
          --build-arg IN_REMOTE=$GITHUB_ACTIONS
        env:
          STRIPE_SECRET_API_KEY: ${{ secrets.STRIPE_SECRET_API_KEY }}
          STRIPE_API_VERSION: ${{ secrets.STRIPE_API_VERSION }}
          ELEPHANT_API_KEY: ${{ secrets.ELEPHANT_API_KEY_TEST }}
          IN_REMOTE: ${{ secrets.IN_REMOTE }}

      - name: Building...
        run: yarn build
